# Generated by Django 4.1.3 on 2023-11-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_game_number_of_players_game_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(null=True),
        ),
    ]
